name:                dont-quote-me
version:             0.1.0.0
github:              "githubuser/dont-quote-me"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dont-quote-me#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - text
  - uuid
  - url
  - stm
  - directory
  - filepath
  - containers
  - rdf4h
  - hsparql
  - http-conduit
  - temporary
  - bytestring
  - errors
  - exceptions

executables:
  dont-quote-me-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dont-quote-me
    - text
    - url
    - transformers
    - aeson
    - blaze-html
    - scotty
    - wai-middleware-static

tests:
  dont-quote-me-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dont-quote-me
    - hspec
